### ISSUE TITLE
few tests fail randomly on Alpinelinux

### ISSUE THREAD

**Issue by andypost** [rosmanov/pecl-eio#24]
Attempted [to package the extension](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/61571) and getting repeatable failures on `armv7` and `armhf` arches.

test log `armv7`
https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1291794
```
TEST 29/29 [tests/fork.phpt]
========DIFF========
     w: 20 l: 20 f: 20 c: 20
002- w: 20 l: 20 f: 20 c: 20
002+ 
003+ Warning: eio_write(): Invalid file descriptor in /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/fork.php on line 15
004+ 
005+ Fatal error: Uncaught Exception: Invalid file descriptor in /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/fork.php:15
006+ Stack trace:
007+ #0 /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/fork.php(15): eio_write(-1, '111111111111111...', 20, 0, 0, Object(Closure), -1)
008+ #1 [internal function]: {closure}('/tmp/tmp_file65...', -1, Resource id #6)
009+ #2 /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/fork.php(23): eio_event_loop()
010+ #3 {main}
011+   thrown in /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/fork.php on line 15
========DONE========
...
TEST 18/29 [tests/eio_seek.phpt]
========DIFF========
--
     int(0)
     resource(5) of type (stream)
     string(6) "567890"
007- int(-1)
007+ Failed to eio_seek
========DONE========
```

Logs from `armhf` https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1291795
```
TEST 8/29 [tests/eio_grp_add.phpt]
========DIFF========
001- resource(%d) of type (EIO Group Descriptor)
002- bool(true)
003- string(%d) "%s"
004- bool(true)
001+ Fatal error: Uncaught TypeError: eio_grp_add(): Argument #2 ($req) must be of type resource, false given in /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/eio_grp_add.php:37
002+ Stack trace:
003+ #0 /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/eio_grp_add.php(37): eio_grp_add(Resource id #6, false)
004+ #1 {main}
005+   thrown in /builds/alpine/aports/testing/php83-pecl-eio/src/eio-3.1.3/tests/eio_grp_add.php on line 37
========DONE========
FAIL Check for eio_grp_add function basic behaviour [tests/eio_grp_add.phpt] 
```

**Comment by rosmanov** [comment]
@andypost I guess, that might be due to some filesystem restrictions imposed on `/tmp/` in that build environment.

In particular, the issue could be related to the fact that the temporary directory is hard-coded:
```php
$filename = '/tmp/tmp_file' .uniqid();
$filename2 = '/tmp/tmp_file2' .uniqid();
```
We should be using `sys_get_temp_dir()` instead. 

Another guess is that there might be a bug in the recent changes in libeio (embedded).

Is there a way for me to reproduce the issue?

Thanks.

**Comment by andypost** [comment]
Sadly it failed only 4 times in CI and then passed , on build servers no issues detected

Maybe some concurrency issue but I failed to figure it out

**Comment by andypost** [comment]
Closing as hard to reproduce
